### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dagilleland** [Programming-0101/Blazor-Marks#1]
Roadmap for simple app:

- [x] Empty Blazor 8 project w. SQLite
- [x] Create database & models
- [ ] Add validation (DataAnnotations)
- [ ] Create CRUD pages
  - *Pure CRUD pages*
  - [x] Marks
    - [x] Initial Scaffolding
    - [x] Index (List all)
    - [x] Edit (Enter a mark/override weight/change name)
    - [x] Details
- [x] Create Course Setup
  - *Simple Business Logic*
    - [x] Page Component
    - [x] BLL Services
  - [x] Courses
    - [x] Index (List all)
    - [x] Create
    - [x] Delete
- [ ] Cleanup Tasks
  - [ ] Remove unused files
  - [ ] #3
  - [ ] Add comments
  - [ ] Add README.md
  - [ ] Add License
  - [ ] Add Credits
  - [ ] Add Resources
  - [ ] Add Roadmap
  - [ ] Add Screenshots
  - [ ] Add Demo
  - [ ] Add Docker Deployment instructions
- [ ] Consider alternate stylesheet, such as Holiday CSS
